name: Pipeline CI/CD - Terraform / Ansible
on:
    workflow_dispatch:
jobs:
    cria-vm:
        name: Provisionamento de VMs
        runs-on: ubuntu-latest
        steps:
            - name: Setup Terraform
              uses: autero1/action-terraform@v3
              with:
                terraform-version: 1.12.2
            - name: Interact with Terraform
              run: terraform --version

            - name: Login to AWS with access keys
              uses: KoalaOps/login-aws@v1
              with:
                aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws_region: us-east-1
                enable_ecr_login: true 

            - name: Checkout Terraform Repo
              uses: actions/checkout@v4              
            
            - name: Terraform init
              working-directory: terraform            
              run: |
                terraform init

            - name: Terraform Validate
              working-directory: terraform              
              run: |
                terraform validate

            - name: Terraform Plan
              working-directory: terraform
              run: |
                terraform plan -out=tfplan
            
            - name: Terraform Apply
              working-directory: terraform 
              run: terraform apply -auto-approve tfplan

            - name: Show Terraform Outputs
              working-directory: terraform
              run: terraform output

            - name: Show files
              run: ls -la

            - name: Show terraform folder
              run: ls -la terraform

