name: Pipeline CI/CD - Terraform / Ansible
on:
    workflow_dispatch:
        inputs:
            action:
                description: "Escolher ação: "
                required: true
                default: "apply"
                type: choice
                options:
                    - apply
                    - destroy
jobs:
    cria-vm:
        name: Criação Automática de Servidor WEB
        runs-on: ubuntu-latest
        steps:
            - name: Setup Terraform
              uses: autero1/action-terraform@v3
              with:
                terraform-version: 1.12.2
            - name: Interact with Terraform
              run: terraform --version

            - name: Login to AWS with access keys
              uses: KoalaOps/login-aws@v1
              with:
                aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws_region: us-east-1
                enable_ecr_login: true 

            - name: Checkout Terraform Repo
              uses: actions/checkout@v4              
            
            - name: Terraform init
              working-directory: terraform            
              run: |
                terraform init

            - name: Terraform Validate
              if: github.event.inputs.action == 'apply'
              working-directory: terraform              
              run: |
                terraform validate

            - name: Terraform Plan
              if: github.event.inputs.action == 'apply'
              working-directory: terraform
              run: |
                terraform plan -out=tfplan
            
            - name: Terraform Apply
              if: github.event.inputs.action == 'apply'
              working-directory: terraform 
              run: terraform apply -auto-approve tfplan

            - name: Terraform Destroy 
              if: github.event.inputs.action == 'destroy' 
              working-directory: terraform 
              run: terraform destroy -auto-approve

            # - name: Show Terraform Outputs
            #   if: github.event.inputs.action == 'apply'
            #   working-directory: terraform
            #   run: terraform output

            # - name: Show files
            #   if: github.event.inputs.action == 'apply'
            #   run: ls -la

            - name: Show terraform folder
              if: github.event.inputs.action == 'apply'
              run: ls -la terraform

            - name: Gerar Inventário Ansible
              if: github.event.inputs.action == 'apply'
              working-directory: terraform
              run: | 
                terraform output -json > tf_output.json

                mkdir -p ../ansible/inventory

                echo "[webserver]" > ../ansible/inventory/hosts

                jq -r '.ec2_ips_named.value[]' tf_output.json | while read ip; do
                  echo "$ip ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> ../ansible/inventory/hosts
                done

                echo "Generated inventory:" 
                cat ../ansible/inventory/hosts
                            
            - name: Configurar chave SSH
              if: github.event.inputs.action == 'apply'
              run: |
                mkdir -p ~/.ssh

                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

                chmod 600 ~/.ssh/id_rsa

            - name: Instalar Ansible
              if: github.event.inputs.action == 'apply'
              run: |
                sudo apt update
                sudo apt install -y ansible

            # - name: Testar conectividade Ansible
            #   if: github.event.inputs.action == 'apply'
            #   run: |
            #     ansible webserver \
            #       -i ansible/inventory/hosts \
            #       -m ping

            - name: Instalar Nginx
              if: github.event.inputs.action == 'apply'
              run: |
                ansible-playbook \
                  -i ansible/inventory/hosts \
                  ansible/playbooks/nginx.yaml
                  
            # - name: Testar Nginx
            #   if: github.event.inputs.action == 'apply'
            #   working-directory: terraform
            #   run: |
            #     IP=$(terraform output -json | jq -r '.ec2_ips_named.value[]')

            #     echo "Testing http://$IP"

            #     curl -I http://$IP

            #     for i in {1..10}; do
            #       if curl -I http://$IP; then
            #         echo "Nginx is up!"
            #         exit 0
            #       fi

            #     echo "Waiting for nginx..."
            #       sleep 5
            #     done

            #         echo "Nginx did not start"
            #         exit 1
            - name: Show application URL
              if: github.event.inputs.action == 'apply'
              working-directory: terraform
              run: |
                echo ""
                echo "===================================="
                echo "Deployment successful!"
                echo "Application URL(s):"
                echo "===================================="

                terraform output -json | \
                  jq -r '.ec2_ips_named.value[]' | \
                  while read ip; do
                    echo "http://$ip"
                  done